import streamlit as st
import pandas as pd
import numpy as np
import random

# Set page configuration to align with the app's theme
st.set_page_config(
    page_title="Data Handling, Outliers, and Fake Data",
    page_icon="🧹",
    layout="wide"
)

st.markdown("# Data Handling, Outliers, and Fake Data")
st.markdown("""
This page addresses the handling of outliers in the dataset and demonstrates the addition of realistic fake data 
for analysis and model improvement.
""")

# Load dataset from session state
if "original_df" in st.session_state:
    # Load the dataset
    df_original = st.session_state.original_df.copy()

    st.markdown("## Original Data")
    st.write(df_original)

    # Handle outliers
    st.markdown("## Outlier Handling")
    st.markdown("""
    Outliers are identified and replaced with the mean of the respective column. Below are the columns processed:
    - **BMI**: Outliers are values more than 1.5 IQRs above the 75th percentile or below the 25th percentile.
    - **Blood Glucose after fasting**: Same approach as BMI.
    """)

    df_handled = df_original.copy()

    def handle_outliers(column):
        q1 = df_handled[column].quantile(0.25)
        q3 = df_handled[column].quantile(0.75)
        iqr = q3 - q1
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr
        mean_value = df_handled[column].mean()
        df_handled[column] = np.where(
            (df_handled[column] < lower_bound) | (df_handled[column] > upper_bound),
            mean_value,
            df_handled[column]
        )

    for column in ["Body Mass Index", "Blood Glucose after fasting"]:
        if column in df_handled.columns:
            handle_outliers(column)

    st.markdown("### Data After Outlier Handling")
    st.write(df_handled)

    # Add realistic fake data
    st.markdown("## Adding Fake Data")
    st.markdown("""
    25–50% realistic fake data has been added to the dataset. Fake data is generated by sampling from 
    the original data's distributions with slight variations.
    """)

    def generate_fake_data(df, count):
        fake_rows = []
        for _ in range(count):
            fake_row = {
                "ID": random.randint(10000, 99999),  # Random unique ID
                "Age": random.randint(df["Age"].min(), df["Age"].max()),
                "Gender": random.choice(df["Gender"].unique()),
                "Body Mass Index": round(
                    random.uniform(df["Body Mass Index"].min(), df["Body Mass Index"].max()), 2
                ),
                "Blood Glucose after fasting": round(
                    random.uniform(df["Blood Glucose after fasting"].min(), df["Blood Glucose after fasting"].max()), 2
                ),
                "Diabetic or not": random.choice(df["Diabetic or not"].unique()),
            }
            fake_rows.append(fake_row)
        return pd.DataFrame(fake_rows)

    fake_data_count = int(len(df_handled) * 0.3)  # Add 30% fake data
    fake_data = generate_fake_data(df_handled, fake_data_count)

    combined_df = pd.concat([df_handled, fake_data], ignore_index=True)

    st.markdown("### Data with Fake Entries")
    st.write(combined_df)

    # Display metrics
    cols = st.columns(2)
    cols[0].markdown("## Original Data Metrics")
    cols[0].dataframe(df_handled.describe())

    cols[1].markdown("## Fake Data Metrics")
    cols[1].dataframe(fake_data.describe())

    st.session_state.combined_df = combined_df

else:
    st.error("Dataset not found. Please navigate back to the main page to load the dataset.")
